version: 2
general:
  branches:
    only:
      - master
      - develop
jobs:
  build:
    working_directory: ~/hmpps-national-search-fe
    docker:
      - image: circleci/node:8.9.1-browsers
    steps:
      - checkout
      - run:
          name: Install awscli
          command: |
            sudo apt install python-pip python-dev
            sudo pip install awscli
            aws --version
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
        name: Install dependencies
        command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - ./node_modules
      - run:
          name: Flow check
          command: yarn flow-check
      - run:
          name: Unit test
          command: yarn test
      - run:
          name: Build
          command: yarn build
