version: 2
general:
  branches:
    only:
      - master
      - develop
jobs:
  build-job:
    working_directory: ~/hmpps-national-search-fe
    docker:
      - image: circleci/node:8.9.1-browsers
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - ./node_modules
      - run:
          name: Flow check
          command: yarn flow-check
      - run:
          name: Unit test
          command: yarn test
      - run:
          name: Build
          command: yarn build
  deploy-job:
    working_directory: ~/hmpps-national-search-fe
      docker:
        - image: circleci/node:8.9.1-browsers
      steps:
        - checkout
        - restore_cache:
            key: dependency-cache-{{ checksum "yarn.lock" }}
        - run:
            name: Install dependencies
            command: yarn install
        - save_cache:
            key: dependency-cache-{{ checksum "yarn.lock" }}
            paths:
              - ~/.cache/yarn
              - ./node_modules
        - run:
            name: Build
            command: yarn build
        - run:
          name: Deploy
          command: aws s3 sync build/ s3://${bucket} --region eu-west-2
workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
              only: master
