version: 2
general:
  branches:
    only:
      - master
      - develop
jobs:
  test-job:
    working_directory: ~/hmpps-national-search-fe
    docker:
      - image: circleci/node:8.9.1-browsers
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - ./node_modules
      - run:
          name: Flow check
          command: yarn flow-check
      - run:
          name: Unit test
          command: yarn test
  build-job:
    working_directory: ~/hmpps-national-search-fe
    docker:
      - image: circleci/node:8.9.1-browsers
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - ./node_modules
      - run:
          name: Build
          command: yarn build
      - persist_to_workspace:
          root: ~/hmpps-national-search-fe
          paths:
            - build
  deploy-job:
      working_directory: ~/hmpps-national-search-fe
      docker:
        - image: circleci/node:8.9.1-browsers
      steps:
        - run:
            name: Install awscli
            command: |
              sudo apt install python-pip python-dev
              sudo pip install awscli
        - attach_workspace:
            at: /tmp/workspace
        - run:
            name: Deploy to AWS
            command: aws s3 sync ~/hmpps-national-search-fe/build/ s3://moj-studio.dnt --acl public-read --sse AES256 --delete

workflows:
  version: 2
  build-deploy:
    jobs:
      - test-job
      - build-job
          requires:
            - test-job
            - build-job
          filters:
            branches:
              only:
                - master
                - develop
      - deploy-job:
          requires:
            - test-job
            - build-job
          filters:
            branches:
              only: master
